# Generated by Django 4.2.7 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Economics'), ('S', 'Science'), ('IT', 'IT')], max_length=20, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата публикации'),
        ),
    ]
